version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=residentes_palme.settings
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  media_volume:
