# Generated by Django 4.2.7 on 2025-08-30 16:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('piso', models.IntegerField(help_text='Piso del apartamento (1-8)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Piso')),
                ('numero', models.CharField(help_text='Identificador único del apartamento (ej: 3B, 5A)', max_length=10, verbose_name='Número de Apartamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
                'db_table': 'apartamentos',
                'ordering': ['edificio__numero', 'piso', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.IntegerField(help_text='Número del edificio (1-32)', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)], verbose_name='Número de Edificio')),
                ('puerta', models.CharField(choices=[('A', 'Puerta A'), ('B', 'Puerta B'), ('I', 'Puerta I'), ('D', 'Puerta D')], help_text='Puerta del edificio (A/B para 1-22, I/D para 23-32)', max_length=1, verbose_name='Puerta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
                'db_table': 'edificios',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(help_text='Nombre completo del residente', max_length=200, verbose_name='Nombre Completo')),
                ('foto', models.ImageField(blank=True, help_text='Foto del residente', null=True, upload_to='residentes/fotos/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residentes', to='residentes.apartamento', verbose_name='Apartamento')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
                'db_table': 'residentes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.AddField(
            model_name='apartamento',
            name='edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to='residentes.edificio', verbose_name='Edificio'),
        ),
        migrations.AlterUniqueTogether(
            name='apartamento',
            unique_together={('edificio', 'piso', 'numero')},
        ),
    ]
