# Generated by Django 4.2.7 on 2025-08-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edificio',
            name='puerta',
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='numero',
            field=models.CharField(help_text='Número del apartamento (ej: 1A, 2B, 3I, 4D)', max_length=10, verbose_name='Número de Apartamento'),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='piso',
            field=models.IntegerField(help_text='Número de piso (1-8)', verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='numero',
            field=models.IntegerField(help_text='Número del edificio (1-32)', unique=True, verbose_name='Número de Edificio'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto opcional del residente', null=True, upload_to='residentes/fotos/', verbose_name='Foto del Residente'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='nombre_completo',
            field=models.CharField(max_length=200, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
    ]
