# Generated by Django 4.2.7 on 2025-08-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0002_remove_edificio_puerta_alter_apartamento_numero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residente',
            options={'ordering': ['tipo', 'nombre_completo'], 'verbose_name': 'Residente', 'verbose_name_plural': 'Residentes'},
        ),
        migrations.AddField(
            model_name='residente',
            name='tipo',
            field=models.CharField(choices=[('propietario', 'Propietario'), ('inquilino', 'Inquilino')], default='inquilino', help_text='Propietario o inquilino del apartamento', max_length=20, verbose_name='Tipo de Residente'),
        ),
        migrations.AlterUniqueTogether(
            name='residente',
            unique_together={('apartamento', 'tipo')},
        ),
    ]
